name: build-docs
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to the docs branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: retypeapp/action-build@v2
      - uses: retypeapp/action-github-pages@v2
        with:
          branch: docs
          directory: docs
          update-branch: true